### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MatthewBraun** [Merijn-DH/p5.js_ios#1]
Line numbers 
Easy beautify code
A settings menu?

**Comment by Merijn-DH** [comment]
I’ll put the line numbers on the list! Thanks for the feedback! What would you like to be in the setting menu?

**Comment by Merijn-DH** [comment]
As well as auto-format code by the way :)

**Comment by Merijn-DH** [comment]
Line numbers added as of version 1.2
Update this week
