### ISSUE TITLE
Keyboard accessory view misalignment

### ISSUE THREAD

**Issue by lenorawillsea** [Merijn-DH/p5.js_ios#2]
First off, thanks for making this app! I’ve really been enjoying using it the last couple weeks.

Now, for the bug report:

The keyboard acccesory view is misaligned on the iPhone X. Screenshot below.

![78eddc1a-99fb-4715-9370-8d934dd3f2ee](https://user-images.githubusercontent.com/13405425/32691454-a82b5c2c-c6bc-11e7-8584-d0503cafb652.png)

**Comment by Merijn-DH** [comment]
Thanks for using the app and for reporting the issue! I indeed had not looked into how things where looking on the iPhone X yet, figuring it should just work fine. I'll look into it soon!

**Comment by Merijn-DH** [comment]
Fixed as of version 1.2
Update coming this week
