### ISSUE TITLE
Change "Run Code" button to a toggle to also "Stop"

### ISSUE THREAD

**Issue by davraamides** [Merijn-DH/p5.js_ios#3]
First, thanks for creating this. It's really easy to use! But I've been killing my battery because I can't find a way to stop execution once it's started. The only way I've been able to stop my code from running is to insert a syntax error and re-run, or to kill the app.

If there is a way you could stop execution and make the "Run Code" button toggle to "Stop" once it's executing, that would be great.

**Comment by Merijn-DH** [comment]
Thanks! Will definitely add this! New version with this version added should be up this week.

**Comment by Merijn-DH** [comment]
Added as of version 1.2
Update this week
